server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportbookingg
    username: root
    password:
  #    // driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
cloudinary:
  cloud-name: di3cbuwx4
  api-key: 996817552155925
  api-secret: pmJw_zzLGnKjz3FGP3itz8IKcDM

app:
  avatar:
    max-size: 5242880 # 5MB
